Cleanup Calcite Workflow
Bodo-inc/calcite pull request #83
Opened 2023-02-15 19:42 UTC by allai5

2023-02-16 19:25 UTC, keatoooon requested changes, later dismissed
Minor nitpick, I would comment these out instead of deleting them, and add a comment as to why. These tests will likely be meaningful when we eventually get around to merging with the upstream.

2023-03-03 01:57 UTC, njriasan commented
@allai5 Can we get this finalized and merged so we can enforce all steps passing?

2023-05-05 00:46 UTC, njriasan commented
I'm going to apply keaton's comments to try retrigger the build.

2023-05-05 00:47 UTC, sahil1105 approved these changes

2023-05-05 00:48 UTC, merged